#!/usr/bin/env node
'use strict';

/**
 * schedule-sweep.js — install/uninstall/status for the daily staleness sweep
 * (macOS launchd only in 0.6.0).
 *
 * The plist does NOT point into the plugin: installed plugins live under a
 * version-numbered cache path that changes on every update. It runs a shim in
 * CONFIG_DIR instead, which re-resolves the current plugin root from the
 * `plugin-root` pointer file that hooks/ensure-deps.js refreshes each
 * session. Baked into the shim at install time: the docs-repo path (cwd),
 * the app key, and the absolute node path (launchd's PATH is nearly empty).
 */

const fs = require('fs');
const os = require('os');
const path = require('path');
const { spawnSync } = require('child_process');
const { parseArgs, resolveAppKey, sweepPath, CONFIG_DIR } = require('./lib/config');

/** Shell-quote a string: wrap in single quotes, escape embedded single quotes. @param {string} s */
function shq(s) {
  return `'${s.replace(/'/g, "'\"'\"'")}'`;
}

/** Escape XML entities in a string. @param {string} s */
function xmlEscape(s) {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

/** Validate app key: must start with alphanumeric, then alphanumeric/dot/underscore/dash. @param {string} appKey */
function assertSafeAppKey(appKey) {
  if (!/^[A-Za-z0-9][A-Za-z0-9._-]*$/.test(appKey)) {
    throw new Error(`App key "${appKey}" contains characters unsafe for launchd artifacts — use letters, digits, dot, underscore, dash.`);
  }
}

/** @param {string} appKey */
function label(appKey) {
  return `com.shopify-apps-doc-writer.sweep.${appKey}`;
}
/** @param {string} appKey */
function plistPath(appKey) {
  return path.join(os.homedir(), 'Library', 'LaunchAgents', `${label(appKey)}.plist`);
}
/** @param {string} appKey */
function shimPath(appKey) {
  return path.join(CONFIG_DIR, `${appKey}.sweep-runner.sh`);
}
/** @param {string} appKey */
function logPath(appKey) {
  return path.join(CONFIG_DIR, `${appKey}.sweep.log`);
}

/**
 * @param {string} at "HH:MM", 24-hour
 * @returns {{hour: number, minute: number}}
 */
function parseAt(at) {
  const m = /^([01]?\d|2[0-3]):([0-5]\d)$/.exec(at);
  if (!m) throw new Error(`--at must be HH:MM (24-hour), got "${at}"`);
  return { hour: Number(m[1]), minute: Number(m[2]) };
}

/**
 * Generate launchd plist XML. Invariant: appKey is pre-validated by
 * assertSafeAppKey() at the CLI boundary and is not re-escaped here.
 * @param {{appKey: string, hour: number, minute: number}} opts
 */
function plistContent({ appKey, hour, minute }) {
  // StartCalendarInterval: launchd runs a missed interval on wake (laptop
  // asleep overnight still sweeps); intervals missed while powered off skip.
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>${xmlEscape(label(appKey))}</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/sh</string>
    <string>${xmlEscape(shimPath(appKey))}</string>
  </array>
  <key>StartCalendarInterval</key>
  <dict>
    <key>Hour</key><integer>${hour}</integer>
    <key>Minute</key><integer>${minute}</integer>
  </dict>
  <key>StandardOutPath</key><string>${xmlEscape(logPath(appKey))}</string>
  <key>StandardErrorPath</key><string>${xmlEscape(logPath(appKey))}</string>
</dict>
</plist>
`;
}

/**
 * Generate shell shim script. Invariant: appKey is pre-validated by
 * assertSafeAppKey() at the CLI boundary and is not re-escaped here.
 * @param {{appKey: string, docsRepo: string, nodePath: string}} opts
 */
function shimContent({ appKey, docsRepo, nodePath }) {
  const pointer = path.join(CONFIG_DIR, 'plugin-root');
  return `#!/bin/sh
# Generated by shopify-apps-doc-writer /docs-schedule — do not edit.
ROOT=$(cat ${shq(pointer)} 2>/dev/null)
if [ -z "$ROOT" ] || [ ! -d "$ROOT" ]; then
  echo "plugin-root pointer missing or stale (${pointer}) — open a Claude Code session to refresh it, then this sweep recovers on its own" >&2
  exit 1
fi
cd ${shq(docsRepo)} || exit 1
exec ${shq(nodePath)} "$ROOT/scripts/sweep.js" --app "${appKey}"
`;
}

/** @returns {number} */
function uid() {
  return process.getuid ? process.getuid() : 0;
}

/** @param {{appKey: string, at: string, docsRepo: string}} opts */
function install({ appKey, at, docsRepo }) {
  const { hour, minute } = parseAt(at);
  fs.mkdirSync(CONFIG_DIR, { recursive: true });
  fs.mkdirSync(path.dirname(plistPath(appKey)), { recursive: true });
  fs.writeFileSync(shimPath(appKey), shimContent({ appKey, docsRepo, nodePath: process.execPath }), { mode: 0o755 });
  fs.writeFileSync(plistPath(appKey), plistContent({ appKey, hour, minute }));
  // Replace any loaded copy: one schedule per app key.
  spawnSync('launchctl', ['bootout', `gui/${uid()}/${label(appKey)}`], { stdio: 'ignore' });
  const res = spawnSync('launchctl', ['bootstrap', `gui/${uid()}`, plistPath(appKey)], { encoding: 'utf8' });
  if (res.status !== 0) {
    throw new Error(`launchctl bootstrap failed (exit ${res.status}): ${res.stderr || res.stdout || ''}`.trim());
  }
  console.log(`Scheduled daily sweep for "${appKey}" at ${at} (docs repo: ${docsRepo}).`);
  console.log(`plist: ${plistPath(appKey)}\nshim:  ${shimPath(appKey)}\nlog:   ${logPath(appKey)}`);
}

/** @param {string} appKey */
function uninstall(appKey) {
  spawnSync('launchctl', ['bootout', `gui/${uid()}/${label(appKey)}`], { stdio: 'ignore' });
  // Remove the record too, so session notices stop.
  for (const f of [plistPath(appKey), shimPath(appKey), sweepPath(appKey), logPath(appKey)]) {
    fs.rmSync(f, { force: true });
  }
  console.log(`Removed the scheduled sweep for "${appKey}".`);
}

/** @param {string} appKey */
function status(appKey) {
  const loaded = spawnSync('launchctl', ['print', `gui/${uid()}/${label(appKey)}`], { stdio: 'ignore' }).status === 0;
  console.log(`plist:  ${fs.existsSync(plistPath(appKey)) ? plistPath(appKey) : 'not installed'}`);
  console.log(`loaded: ${loaded}`);
  if (fs.existsSync(sweepPath(appKey))) {
    const record = JSON.parse(fs.readFileSync(sweepPath(appKey), 'utf8'));
    console.log(`last sweep: ${record.at} — ${record.status}`);
  } else {
    console.log('last sweep: never ran');
  }
  console.log(`log: ${logPath(appKey)}`);
}

function main() {
  if (process.platform !== 'darwin') {
    console.error('Scheduled sweeps are macOS-only in 0.6.0 (launchd). Linux cron is deferred.');
    process.exit(1);
  }
  const args = parseArgs(process.argv.slice(2));
  const modes = ['install', 'uninstall', 'status'].filter((m) => args[m]);
  if (modes.length !== 1) {
    console.error(
      'Usage: node scripts/schedule-sweep.js --install --app <key> [--at HH:MM]   (run from the docs repo)\n' +
        '   or: node scripts/schedule-sweep.js --uninstall --app <key>\n' +
        '   or: node scripts/schedule-sweep.js --status --app <key>'
    );
    process.exit(1);
  }
  const appKey = resolveAppKey(/** @type {string|undefined} */ (typeof args.app === 'string' ? args.app : undefined));
  try {
    assertSafeAppKey(appKey);
    if (args.install) install({ appKey, at: typeof args.at === 'string' ? args.at : '03:00', docsRepo: process.cwd() });
    else if (args.uninstall) uninstall(appKey);
    else status(appKey);
  } catch (err) {
    console.error(err.message);
    process.exit(1);
  }
}

if (require.main === module) main();

module.exports = { parseAt, plistContent, shimContent, label, plistPath, shimPath, logPath, shq, xmlEscape, assertSafeAppKey };
